version: '2'
services:
  redis:
    profiles:
      - backend
      - data
      - all
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-cache:/data
  db:
    profiles:
      - backend
      - data
      - all
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db-cache:/data/db
  api:
    profiles:
      - backend
      - all
    image: pixel_api:local
    build: ./pixel-canvas-api
    restart: always
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - 4000:4000
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_ADDR: db
      REDIS_ADDR: redis
  ui:
    profiles:
      - frontend
      - all
    image: pixel_ui:local
    build: ./pixel-canvas-ui
    restart: always
    depends_on:
      - api
    ports:
      - 3000:80